---
title: "2023년 6월 학습동아리 자료"
output: html_document
date: "2023-04-19"
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# MarkDown문서를 활용하면 좋은 점!

그래프 자료를 동적인 상태로 확인할 수 있습니다.
다음의 아래와 같은 형식으로 자료를 주고받을 수 있죠.

```{r cars}
summary(cars)
```

## 인터렉티브 그래프

You can also embed plots, for example:

```{r plotly, message=FALSE}
library(plotly)
library(ggplot2)

p <- ggplot(mpg, aes(displ, hwy, color = drv)) + geom_point()

ggplotly(p)

a <- ggplot(diamonds, aes(cut, fill = clarity)) +
  geom_bar(position = "dodge")

ggplotly(a)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

Markdown 문서를 활용하면, 정적인 자료를 동적인 상태로 확인할 수 있습니다. 하핫!

```{r}
#인터랙티브 시계열
library(dygraphs)
library(tidyverse)

economic <- economics
head(economic)
library(xts)
eco <- xts(economic$unemploy, order.by = economic$date)
head(eco)
dygraph(eco) %>% dyRangeSelector()

eco_a <- xts(economic$psavert, order.by = economic$date)
eco_b <- xts(economic$unemploy, order.by = economic$date)
rownames_to_column(as.data.frame(eco_a), var = "date") %>% head(5)
eco_a %>% head
eco_b %>% head

eco2 <- cbind(eco_a, eco_b)
head(eco2)

colnames(eco2) <- c("psavert", "unemploy")
head(eco2)
dygraph(eco2) %>% dyRangeSelector()

```

**어떠세요** 신기하지 않나요?

